version: '3.6'

services:
    custompios:
        image: guysoft/custompios:devel
        container_name: myscriptpios-build
        tty: true
        restart: always
        privileged: true
        volumes:
        - ./MyScriptOS/src/:/distro
        devices:
        - /dev/loop-control