#!/usr/bin/env bash
# MyScript-Installer
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

# Install Node
curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
sudo apt-get --yes install nodejs

# Install MyScript
mkdir /home/pi/MyScript
unpack /filesystem /home/pi/MyScript

sudo npm install -g pm2
cd /home/pi/MyScript
pm2 start myscript.js
pm2 startup systemd
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u pi --hp /home/pi